_commit: v1.9.0-1-g02b6330
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: true
helmCrds: false
helmName: external-dns
helmRelease: external-dns-pihole
helmRepo: https://kubernetes-sigs.github.io/external-dns/
helmValues: helm/values.yaml
helmVersion: ''
homepageEnabled: false
ingress: false
labels: |-
  app.kubernetes.io/instance: external-dns-pihole
  app.kubernetes.io/name: pihole
name: external-dns-pihole
namespace: external-dns-pihole
pvc: false
reloader: true
resources:
- external-secrets.yaml
service: false
serviceAccount: false
upstreamURL: https://github.com/kubernetes-sigs/external-dns
url: https://github.com/charlesthomas/homelab-external-dns-pihole
