---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns-pihole

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-external-dns-pihole
commonLabels:
  app.kubernetes.io/instance: external-dns-pihole
  app.kubernetes.io/name: pihole

resources:
- resources/deployments.yaml
- resources/external-secrets.yaml
- resources/namespaces.yaml
- resources/rbac.yaml
- resources/service-accounts.yaml
- resources/services.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: external-dns-pihole
      namespace: external-dns-pihole
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
