---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns-pihole

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-external-dns-pihole
commonLabels:
  app.kubernetes.io/instance: external-dns-pihole
  app.kubernetes.io/name: pihole

resources:
- resources/external-secrets.yaml
- resources/namespaces.yaml
patches:
- patch: |-
<<<<<<< before updating
    apiVersion: apps/v1
    kind: Deployment
=======
    apiVersion: networking.k8s.io/v1
    kind: Ingress
>>>>>>> after updating
    metadata:
      name: external-dns-pihole
      namespace: external-dns-pihole
      annotations:
<<<<<<< before updating
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
=======
        gethomepage.dev/href: https://external-dns-pihole.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: 
        gethomepage.dev/group: 
        gethomepage.dev/icon: external-dns-pihole
        gethomepage.dev/name: external-dns-pihole
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
>>>>>>> after updating
helmCharts:
- name: external-dns
  namespace: external-dns-pihole
  releaseName: external-dns-pihole
  repo: https://kubernetes-sigs.github.io/external-dns/
  valuesFile: helm/values.yaml
