---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-pihole
  namespace: external-dns-pihole
  labels:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/instance: external-dns-pihole
